name: CI

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3.3.4
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git pkg-config google-chrome-stable

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3.3.4
          bundler-cache: true

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bin/test

      - name: Generate coverage badge
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir -p .github/badges
          COVERAGE=$(ruby -e 'require "json"; puts JSON.parse(File.read("coverage/.last_run.json"))["result"]["line"].to_i')
          COLOR=$([ $COVERAGE -ge 90 ] && echo "brightgreen" || ([ $COVERAGE -ge 80 ] && echo "yellow" || echo "red"))
          curl -o .github/badges/coverage.svg "https://img.shields.io/badge/coverage-${COVERAGE}%25-${COLOR}"

      - name: Commit and push coverage badge
        if: github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .github/badges/coverage.svg
          git commit -m "Update coverage badge" || echo "No changes to commit"
          git push

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore

